Avoid compile error on macos mojave
ElementsProject/lightning pull request #4019
Opened 2020-09-08 13:20 UTC by Moller40

Fixing the following error by adding the number of items in
'enum feerate' to the end of it.

lightningd/bitcoind.c:183:29: error: result of comparison of constant
8 with expression of type 'enum feerate' is always true [-Werror,
-Wtautological-constant-out-of-range-compare]
        for (enum feerate f = 0; f < NUM_FEERATES; f++) {
                                 ~ ^ ~~~~~~~~~~~~

Changelog-Fixed: compile error on macos

2020-09-08 23:58 UTC, rustyrussell commented
No, the compiler is *wrong* here.  (It's true for C++, not C).

My preferred fix is to change `f` to an `int`, i.e.:

```C
for (int f = 0; f < NUM_FEERATES; f++) {
```

2020-09-08 23:59 UTC, rustyrussell requested changes
Please just change f to an int, check if that fixes compile?

2020-09-09 02:18 UTC, Moller40 commented
Yes, changing f to an int also fixes it.

2020-09-09 10:02 UTC, cdecker commented
ACK https://github.com/ElementsProject/lightning/pull/4019/commits/ea61f4867bd192680a3b9325802fa71da944dd0f

2020-09-09 11:13 UTC, merged

2020-09-09 11:13 UTC, rustyrussell commented
Thanks!