Strip the type and length prefix from the custommsg hook call
ElementsProject/lightning pull request #4394
Opened 2021-02-23 10:47 UTC by cdecker

We were always prefixing the `message` field with the internal type
prefix 0x0407, followed by the length prefix. Neither is needed since
the type being constant is of no interest to the plugin and the length
being implicit due to the JSON-encoding.

Reported-by: Ilya Evdokimov

2021-02-24 01:49 UTC, rustyrussell requested changes

2021-02-24 01:49 UTC, rustyrussell commented on lightningd/peer_control.c
> +#ifdef COMPAT_V093
This is not a COMPAT_V093 thing!  This is a deprecated_apis thing.

COMPAT_V093 means "if you first started this node at 0.9.3, we will still work".  It's mainly for database fields, but can also apply to existing channels with peers.

2021-02-24 01:49 UTC, rustyrussell commented on tests/plugins/custommsg_a.py
>          peer_id=peer_id
This should probably be simply rolled into the previous one, since otherwise there's bisect breakage.

It's pretty small...

2021-03-01 14:37 UTC, cdecker commented
Removed the `COMPAT_V093` flag, replaced it with `deprecated_apis`, and squashed the two commits into one :+1:

2021-03-02 04:11 UTC, rustyrussell commented
Ack https://github.com/ElementsProject/lightning/commit/96e9d79233348754011fb8af26e972788dbb389e

2021-03-02 04:11 UTC, merged