added the default bitcoin path for macos to startup_regtest.sh
ElementsProject/lightning pull request #4408
Opened 2021-03-03 08:38 UTC by renepickhardt

The `contrib/startup_regtest.sh` script does not work out of the box on mac os as the default bitcoin dir in mac os is not `~/.bitcoin` but rather `~/Library/Application Support/Bitcoin/` so I added that

2021-03-03 08:41 UTC, renepickhardt commented
While at this we might want to fix at least the readme of the file to address https://github.com/ElementsProject/lightning/issues/4400

2021-03-03 08:45 UTC, renepickhardt commented
Also I don't understand why the smoketests fail when just touching a helper script that has barely anything todo with c-lightning in itself.

2021-03-03 17:57 UTC, cdecker requested changes

2021-03-03 17:57 UTC, cdecker commented on contrib/startup_regtest.sh
> +	    if [ -d "$HOME/Library/Application Support/Bitcoin/" ]; then
Maybe better avoid an extra level of indentation using `elif` instead of `else if`.

2021-03-03 18:01 UTC, cdecker commented
Regarding CI failing, I'll have to give it a got tomorrow, might just be that an error was grandfathered in and manifests now.

2021-03-03 18:02 UTC, cdecker commented
Nope, I missed it at first, but it seems you updated the submodule version of libwally-core. Reverting that should work again.

2021-03-03 22:40 UTC, niftynei commented
concept ACK, modulo @cdecker's most excellent suggestions for improvement.

thanks for this!

2021-03-11 04:18 UTC, rustyrussell commented
OK, did those minor cleanups, repushed.

2021-03-16 00:10 UTC, merged