Plugin misconfig
ElementsProject/lightning pull request #4418
Opened 2021-03-09 10:17 UTC by cdecker

# Add early abort in case of misconfigured plugins

There are ways to misconfigure plugins that will cause us to shut
down. These include having an important plugin fight for a method name
with another plugin, e.g., by loading the same plugin twice. Until now
we would happily continue with the startup sequence only to later
realize that we were supposed to shutdown, but by then we'd have
buried the error message in the logs.

This PR just adds a check for misconfigurations before we even start
the normal `io_loop`, avoiding expensive initializations and not
hiding the log entries about the cause. This works if we're just using
`--help` as well, and produces a much clearer picture of what is going
on.

I also added the name of the plugin that was clashing with RPC methods.

Fixes #4415
Reported-by: PsySc0rpi0n
Reported-by: Ján Sáreník <@jsarenik>

2021-03-09 10:47 UTC, jsarenik commented
Thank you @cdecker!

Currently it hangs which is pretty good because it would not infinitely restart on `systemd`/`daemontools` setups:

```
$ lightningd --testnet --plugin=/tmp/backup/backup.py --plugin=$HOME/src/plugins/backup/backup.py
...
2021-03-09T10:44:34.704Z DEBUG   plugin-manager: started(42331) /tmp/backup/backup.py
2021-03-09T10:44:34.713Z DEBUG   plugin-manager: started(42332) /home/nsm/src/plugins/backup/backup.py
2021-03-09T10:44:34.795Z UNUSUAL plugin-backup.py: Killing plugin: Could not register method "backup-compact", a method with that name is already registered by plugin /tmp/backup/backup.py
^C
```

ACK 7bafc5766

2021-03-09 10:51 UTC, jsarenik requested changes

2021-03-09 10:51 UTC, jsarenik commented on lightningd/lightningd.c
> +		fatal("Could not initialize the plugins, see above for details.");
@cdecker seemingly I never get here

2021-03-09 11:17 UTC, cdecker commented
That's strange, it doesn't hang when I test it locally. Hanging is definitely the wrong thing to do here.

2021-03-09 11:19 UTC, cdecker commented
Notice that we don't exit if a non-important plugin dies. Please use `--important-plugin` instead @jsarenik, I expect your test is actually starting correctly but not printing anything since you have `--log-level=info` and it's actually working fine.

2021-03-10 17:23 UTC, jsarenik commented
@cdecker Thanks for info. `--important-plugin` really helps. By the way I have `log-lever=debug`, just cherry-picking when pasting here.

```
$ lightningd --testnet --important-plugin=/tmp/backup/backup.py --important-plugin=$HOME/src/plugins/backup/backup.py
...
$ ~/service/lightningd-testnet-esplora/run 
2021-03-10T17:22:53.769Z DEBUG   plugin-manager: blacklist for bcli
2021-03-10T17:22:53.769Z INFO    plugin-manager: /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/bcli: disabled via disable-plugin
2021-03-10T17:22:53.769Z DEBUG   plugin-manager: blacklist for bcli
2021-03-10T17:22:53.769Z INFO    plugin-manager: /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/bcli: disabled via disable-plugin
2021-03-10T17:22:53.770Z DEBUG   plugin-manager: started(38680) /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/autoclean
2021-03-10T17:22:53.771Z DEBUG   plugin-manager: started(38681) /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/fetchinvoice
2021-03-10T17:22:53.772Z DEBUG   plugin-manager: started(38682) /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/keysend
2021-03-10T17:22:53.773Z DEBUG   plugin-manager: started(38683) /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/offers
2021-03-10T17:22:53.782Z DEBUG   plugin-manager: started(38684) /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/pay
2021-03-10T17:22:53.790Z DEBUG   plugin-manager: started(38685) /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/txprepare
2021-03-10T17:22:53.796Z DEBUG   plugin-manager: started(38686) /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/spenderp
2021-03-10T17:22:53.806Z DEBUG   plugin-manager: started(38687) /home/nsm/lightning-my/bin/../libexec/c-lightning/plugins/esplora
2021-03-10T17:22:53.814Z DEBUG   plugin-manager: started(38688) /tmp/backup/backup.py
2021-03-10T17:22:53.823Z DEBUG   plugin-manager: started(38689) /home/nsm/src/plugins/backup/backup.py
2021-03-10T17:22:53.838Z INFO    plugin-esplora: getutxout
2021-03-10T17:22:53.924Z UNUSUAL plugin-backup.py: Killing plugin: Could not register method "backup-compact", a method with that name is already registered by plugin /tmp/backup/backup.py
2021-03-10T17:22:53.924Z **BROKEN** plugin-backup.py: Plugin marked as important, shutting down lightningd!
Could not initialize the plugins, see above for details.
```

ACK 7bafc57

2021-03-10 17:25 UTC, jsarenik commented on lightningd/lightningd.c
> +		fatal("Could not initialize the plugins, see above for details.");
Apologies, I thought that `important` flag is set in plugin details automatically. All good now. Thank you.

2021-03-10 18:02 UTC, niftynei approved these changes
ACK 7bafc5766bd3d0eabb2ad6f2d0a6b4dc7209ee64

2021-03-10 18:03 UTC, merged