lightningd: implement --log-timestamps=false.
ElementsProject/lightning pull request #4504
Opened 2021-05-03 03:22 UTC by rustyrussell

Fixes: #4494
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
Changelog-Added: config: New option `log-timestamps` allow disabling of timestamp prefix in logs.

2021-05-04 09:59 UTC, jsarenik requested changes
Thank you Rusty!

2021-05-04 09:59 UTC, jsarenik commented on doc/lightningd-config.5
> +Set this to false to turn of timestamp prefixes (they will still appear
to turn off

2021-05-04 09:59 UTC, jsarenik commented on doc/lightningd-config.5.md
> +Set this to false to turn of timestamp prefixes (they will still appear
"to turn off", ah this is the source and the other is generated from this

2021-05-04 10:03 UTC, jsarenik commented on doc/lightningd-config.5
> +Set this to false to turn of timestamp prefixes (they will still appear
see below (this one is generated)

2021-05-04 13:18 UTC, cdecker commented
Just a minor typo in the docs.

ACK https://github.com/ElementsProject/lightning/pull/4504/commits/7e8d771acfd595260f802f1fd973f09421570c62

2021-05-04 13:19 UTC, cdecker approved these changes

2021-05-04 22:00 UTC, vincenzopalazzo approved these changes
ack https://github.com/ElementsProject/lightning/pull/4504/commits/7e8d771acfd595260f802f1fd973f09421570c62

2021-05-05 06:57 UTC, rustyrussell commented
Typo fixed, thanks!

2021-05-05 11:19 UTC, jsarenik commented
ACK 451e1898c

2021-05-05 11:30 UTC, jsarenik approved these changes

2021-05-05 22:19 UTC, merged