libhsmd(python): Use proper tmpctx management and fix embarassing oversights
ElementsProject/lightning pull request #4543
Opened 2021-05-18 13:43 UTC by cdecker

We were:

 - Not setting up and clearing `tmpctx` correctly.
 - Not using `common_setup`
 - Using the message, instead of the `peer_id` to derive secrets :facepalm:

2021-05-25 20:22 UTC, niftynei commented on contrib/libhsmd_python/setup.py
> +                    "https://github.com/cdecker/lightning.git"
comma missing here seems like a mistake?

2021-05-25 20:57 UTC, rustyrussell requested changes

2021-05-25 20:57 UTC, rustyrussell commented on contrib/libhsmd_python/setup.py
> +                    "https://github.com/cdecker/lightning.git"
Good catch!

2021-05-30 10:18 UTC, rustyrussell approved these changes

2021-05-30 10:19 UTC, rustyrussell commented
Ack https://github.com/ElementsProject/lightning/commit/f796e58108f49023874e6d607be2926cb97ff42d

2021-05-30 10:19 UTC, merged