Issue #4720 Restrict channel fee updates…
ElementsProject/lightning pull request #4756
Opened 2021-09-02 00:11 UTC by ddustin

for leased channels to be less than comitted rates for both individual channels as well as group sets. If any channel being updated is above committed limits, abort the fee setting.

2021-09-04 10:08 UTC, cdecker requested changes
Currently the `test_setchannelfee_all` CI test is broken (timeout).

2021-09-07 02:02 UTC, ddustin commented on lightningd/peer_control.c
> +		assert(channel->lease_chan_max_ppt * 1000 < channel->lease_chan_max_ppt);
The goal was to check for integer wrapping. I'll add a comment explaining that

2021-09-14 16:10 UTC, cdecker reviewed
Thanks for the fixups, sadly tests seems not to be too happy:

 - `test_setchannelfee_all`: might be hitting the restriction despite not being a leased channel, maybe the lease detection is not working?
 - `test_channel_lease_post_expiry` complains about `setfeerates` being unavailable (call introduced in the first commit, not sure why it's not failing everywhere)

Otherwise I look forward to merging this :-)

2021-09-18 04:49 UTC, ddustin commented
> Thanks for the fixups, sadly tests seems not to be too happy:
> 
> 
> 
>  - `test_setchannelfee_all`: might be hitting the restriction despite not being a leased channel, maybe the lease detection is not working?
> 
>  - `test_channel_lease_post_expiry` complains about `setfeerates` being unavailable (call introduced in the first commit, not sure why it's not failing everywhere)
> 
> 
> 
> Otherwise I look forward to merging this :-)

Thanks for the comments!

I thought these would be easier to resolve once I got the test framework working on my computer (I use a Mac).

So I pivoted to doing that first, then I plan on polishing off this PR =)

2021-09-27 08:22 UTC, ddustin commented on lightningd/peer_control.c
> -/* Comment added to satisfice AUTODATA */
I believe the filename is only accessible as "" type string literal, sadly. I don't think it's normalized either.

2022-09-21 14:14 UTC, cdecker commented
Wondering if we can bring this up to date and add it to the merge-train :-)

2022-09-21 21:06 UTC, ddustin commented
> Wondering if we can bring this up to date and add it to the merge-train :-)

Workin on getting all my PRs merge-train ready this week! =)

2022-09-28 21:53 UTC, ddustin commented
> Awesome, can't wait for your changes to land 🚀

This one got pretty stale 😳 -- Gonnna look at this again a little later.

2023-09-18 05:53 UTC, rustyrussell commented
Closing this under the "too old" rule...  Feel free to fix up and reopen!

2023-09-18 05:53 UTC, closed without merging