Delay fee changes
ElementsProject/lightning pull request #4806
Opened 2021-09-22 05:06 UTC by rustyrussell

2021-09-22 08:28 UTC, vincenzopalazzo requested changes
LGTM https://github.com/ElementsProject/lightning/pull/4806/commits/7871e8b1be377cdff28f3fbe6912f452b1b8f932

Only a small change request on the doc, the sequence between `\[` and `\*` it is always tricky

2021-09-22 08:28 UTC, vincenzopalazzo commented on doc/lightning-setchannelfee.7.md
> +**setchannelfee** *id* \[*base*\] \[*ppm*\] [\*enforcedelay\*]
```suggestion
**setchannelfee** *id* \[*base*\] \[*ppm*\] \[*enforcedelay*\]
```

2021-09-23 08:07 UTC, vincenzopalazzo approved these changes
ack https://github.com/ElementsProject/lightning/pull/4806/commits/25acf5a46f953e6610c594f4e8dffa977fd7df94

2021-09-23 13:05 UTC, cdecker approved these changes
ACK 25acf5a46f953e6610c594f4e8dffa977fd7df94

2021-09-23 13:05 UTC, merged