devtools/featuretool
ElementsProject/lightning pull request #4807
Opened 2021-09-22 06:21 UTC by rustyrussell

I found this easier than reading hex.

Changelog-None

2021-09-22 08:19 UTC, vincenzopalazzo commented on devtools/Makefile
> +devtools/features: $(CCAN_OBJS) common/features.o common/utils.o wire/fromwire.o wire/towire.o devtools/features.o
```suggestion
devtools/features: $(CCAN_OBJS) common/features.o common/utils.o wire/fromwire.o wire/towire.o common/features.o
```

maybe this should work?

2021-09-22 08:20 UTC, vincenzopalazzo requested changes
LGTM https://github.com/ElementsProject/lightning/pull/4807/commits/7d77d50d86147e3f3e97e8dcddb168a793ac49d9

Only a small comment on the Makefile.

2021-09-22 09:59 UTC, rustyrussell commented
No, I forgot to commit the actual tool!

2021-09-22 11:35 UTC, vincenzopalazzo requested changes
by following the GH actions suggestion I think here there is a call missing? and I'm curious to know it is used to make sure that the str operation works well.

2021-09-22 11:35 UTC, vincenzopalazzo commented on devtools/features.c
> +	const u8 *features;
```suggestion
	const u8 *features;
	
	setup_locale();
```

2021-09-22 11:35 UTC, vincenzopalazzo commented
>No, I forgot to commit the actual tool!

Ops, my mistake sorry!

2021-09-23 02:39 UTC, rustyrussell commented
Rebase, and fix the missing setup_locale(), thanks @vincenzopalazzo

2021-09-23 08:03 UTC, vincenzopalazzo approved these changes
ack https://github.com/ElementsProject/lightning/pull/4807/commits/cd6454d9d06bcc9a21a6eeb1bcda67eabd6647b4

2021-09-23 13:02 UTC, merged