Correcting: 'needs' instead of 'need'
ElementsProject/lightning pull request #4835
Opened 2021-10-03 07:50 UTC by jerzybrzoska

2021-10-03 08:55 UTC, vincenzopalazzo requested changes
LGTM.

Only a small change request

2021-10-03 08:55 UTC, vincenzopalazzo commented on README.md
> +If you encrypt your `hsm_secret`, you will have to pass the `--encrypted-hsm` startup option to `lightningd`. Once your `hsm_secret` is encrypted, you __will not__ be able to access your funds withou
```suggestion
If you encrypt your `hsm_secret`, you will have to pass the `--encrypted-hsm` startup option to `lightningd`. Once your `hsm_secret` is encrypted, you __will not__ be able to access your funds without your password, so please beware with your password management. Also, beware of not feeling too safe with an encrypted `hsm_secret`: unlike for `bitcoind` where the wallet encryption can restrict the usage of some RPC command, `lightningd` always needs to access keys from the wallet which is thus __not locked__ (yet), even with an encrypted BIP32 master seed.
```

2021-10-04 10:16 UTC, cdecker commented
ACK https://github.com/ElementsProject/lightning/pull/4835/commits/c7473a128c7d84652dae05ffe2fcb3587f4e5b90

2021-10-04 10:19 UTC, vincenzopalazzo approved these changes
ack https://github.com/ElementsProject/lightning/pull/4835/commits/c7473a128c7d84652dae05ffe2fcb3587f4e5b90

2021-10-04 10:32 UTC, jerzybrzoska commented
> LGTM.
> 
> Only a small change request

`lightningd` is singular third person, therefore the use of **needs** is warranted. I may be wrong, am I? [Reference](https://ell.stackexchange.com/questions/83380/can-i-use-needs-in-this-sentence).

2021-10-04 13:01 UTC, michaelfolkson commented
I think the second commit adding a comma went wrong as it has co-authors. Regardless, I think there should only be one commit for a change like this and so squashing commits may be required.

ACK the change once it is a single commit.

2021-10-06 12:49 UTC, cdecker commented
Squashed the commits into a single one

ACK https://github.com/ElementsProject/lightning/pull/4835/commits/8e4ef58e1ad775ec31e90982752bffa2fa4a7dfd

2021-10-06 14:17 UTC, merged