Websocket fix
ElementsProject/lightning pull request #4945
Opened 2021-12-02 07:15 UTC by rustyrussell

I noticed that experimental-websocket-port didn't work on my node (it crashed).  Along the way, I found a bug in DNS handling.

2021-12-02 09:28 UTC, SimonVrouwe commented
Maybe off-topic, when I run `test_announce_and_connect_via_dns` on my local machine it fails with:
```
connectd: DNS with getaddrinfo gave: Name or service not known
```
Because that test expects a `localhost.localdomain` to be present?
`'announce-addr': ['localhost.localdomain:12345'],  # announce dns`

But my machine (Debian) has `.lan` instead of `.localdomain`:
```
$ host localhost
localhost.lan has address 127.0.0.1
localhost.lan has IPv6 address ::1

```
Changing  `.localdomain` to `.lan` makes the test pass, but is it correct?

2021-12-02 09:43 UTC, m-schmoock commented
> Changing .localdomain to .lan makes the test pass, but is it correct?

Yes it works, no its not correct. I was the assumption that "localdomain" is some sort of standard. Turns out it isn't. I didn't want to go for just "localhost" (which would work) because it can trigger certain internal code paths that shortcut address resolution to 127.0.0.1. I wanted the test to be in a way that it needs to run for getaddrinfo and let the system decide.

2021-12-02 09:48 UTC, m-schmoock requested changes
Sure, when Websockets have empty addresses this should now work. Good that its now test covered.

Imho, the way `opt_add_addr_withtype` works is a little too iffy. But I also don't have a better idea.

2021-12-02 09:48 UTC, m-schmoock commented on tests/test_connection.py
> +                                                     '127.0.0.1: '+ str(port2)],
Nit, and CI already found it: `E225 missing whitespace around operator`

2021-12-02 14:41 UTC, SimonVrouwe commented
> > Changing .localdomain to .lan makes the test pass, but is it correct?
> 
> Yes it works, no its not correct. I was the assumption that "localdomain" is some sort of standard. Turns out it isn't. I didn't want to go for just "localhost" (which would work) because it can trigger certain internal code paths that shortcut address resolution to 127.0.0.1. I wanted the test to be in a way that it needs to run for getaddrinfo and let the system decide.

It looks you can test what you have locally (`.lan` or `.localdomain`) using:
`socket.getaddrinfo('localhost.localdomain', '12345') `
returning error (or not): `gaierror: [Errno -2] Name or service not known`

2021-12-02 14:53 UTC, m-schmoock commented
One stupid fix would be to add `127.0.0.1   localhost.localdomain` to your `/etc/hosts`. But thats just a temporary solution if your annoyed by the test failing.

2021-12-02 17:58 UTC, SimonVrouwe commented
> One stupid fix would be to add `127.0.0.1 localhost.localdomain` to your `/etc/hosts`. But thats just a temporary solution if your annoyed by the test failing.

Thanks, add it as an alias in `/etc/hosts`, like this:
`127.0.0.1       localhost localhost.localdomain`
and still works after restarting NetworkManager, so seems permanent.

2021-12-02 23:06 UTC, rustyrussell commented
We should reduce the scope of the localhost parsing perhaps: use it as a fallback iff no_dns is set, otherwise resolve it like anything else?

2021-12-04 21:17 UTC, vincenzopalazzo approved these changes
ack https://github.com/ElementsProject/lightning/pull/4945/commits/729eace38d9bc456bb72f3d8b150b204fc0b2336

CI looks like fixed with https://github.com/ElementsProject/lightning/pull/4954

2021-12-04 21:53 UTC, m-schmoock commented
ack 729eace

2021-12-04 21:53 UTC, m-schmoock approved these changes

2021-12-05 04:24 UTC, rustyrussell commented
Trivial rebase on master to fix flake.

2021-12-05 15:42 UTC, m-schmoock commented
ACK 6c21a6b

I restarted CI because it failed at flaky but unrelated `tests/test_pay.py::test_fetchinvoice_3hop`. Now its all good.

2021-12-05 15:43 UTC, merged

2021-12-05 15:43 UTC, m-schmoock commented
Whohoo, didn't know I had the permissions to do so, but the merge worked <3