pytest: restore gossip advertizement tests for default port.
ElementsProject/lightning pull request #4958
Opened 2021-12-06 06:47 UTC by rustyrussell

Follows #4900 which I've now merged.

Changelog-None

2021-12-06 06:52 UTC, vincenzopalazzo requested changes

2021-12-06 06:52 UTC, vincenzopalazzo commented on tests/test_gossip.py
> +        {'type': 'torv3', 'address': 'vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion', 'port': 19846},
In the case of Elements this test will fail.

We need somethings like if `19846 l1.info["network"] == "testnet" else 2xxx`

2021-12-09 12:03 UTC, jsarenik commented
Concept ACK. Apologies for removing those lines @rustyrussell.

What about this diff against current master:

```diff
diff --git a/tests/test_gossip.py b/tests/test_gossip.py
index 466238d73..6c67ca64d 100644
--- a/tests/test_gossip.py
+++ b/tests/test_gossip.py
@@ -1016,10 +1016,15 @@ def test_query_short_channel_id(node_factory, bitcoind, chainparams):
 
 
 def test_gossip_addresses(node_factory, bitcoind):
+    # defoult port for either regtest or Liquid
+    default_port = 19846 if ln.info["network"] is "regtest" else 20735
     l1 = node_factory.get_node(options={
         'announce-addr': [
             '[::]:3',
+            '[::]',
             '127.0.0.1:2',
+            '127.0.0.1',
+            'vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion'
             '4acth47i6kxnvkewtm6q7ib2s3ufpo5sqbsnzjpbi7utijcltosqemad.onion:1234'
         ],
     })
@@ -1034,7 +1039,10 @@ def test_gossip_addresses(node_factory, bitcoind):
     nodes = l2.rpc.listnodes(l1.info['id'])['nodes']
     assert len(nodes) == 1 and nodes[0]['addresses'] == [
         {'type': 'ipv4', 'address': '127.0.0.1', 'port': 2},
+        {'type': 'ipv4', 'address': '127.0.0.1', 'port': default_port},
         {'type': 'ipv6', 'address': '::', 'port': 3},
+        {'type': 'ipv6', 'address': '::', 'port': default_port},
+        {'type': 'torv3', 'address': 'vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion', 'port': default_port},
         {'type': 'torv3', 'address': '4acth47i6kxnvkewtm6q7ib2s3ufpo5sqbsnzjpbi7utijcltosqemad.onion', 'port': 1234},
     ]
 
```

2021-12-13 23:13 UTC, rustyrussell commented
Trivial rebase, and fix for elements default port.

Ack 08f3b161a

2021-12-14 03:11 UTC, merged