add 'perl' dependency for 'build on fedora'
ElementsProject/lightning pull request #5321
Opened 2022-06-15 13:56 UTC by NicolaLS

Building on Fedora Linux 36 (Workstation Edition) x86_64 failed with an error pointing me to [this](https://github.com/openssl/openssl/issues/13761#issue-777412186). Installing perl fixed it for me

2022-06-15 14:42 UTC, vincenzopalazzo approved these changes
utACK  [45eb9db](https://github.com/ElementsProject/lightning/pull/5321/commits/45eb9db921e0629c2dd1f7e72f9e3bbc5c0ea224)

2022-07-02 08:35 UTC, wtogami commented
Overall the Fedora build instructions in that doc are old. I'd like to test it with a minimal build environment of Fedora 36, RHEL8 and RHEL9, and do a big cleanup PR.

2022-07-02 08:46 UTC, wtogami commented
I'm building CLN just fine on Fedora 35 and 36 without perl installed. If you're referring to `FindBin.pm` in particular like in the link you referenced that is not contained in Fedora's `perl` package but rather `perl-FindBin`.

Let's figure out why my results without perl installed builds CLN and you have different results.

Could you please post the exact build errors you're seeing? Can I see the output of `./configure` before you build?

2022-07-02 08:49 UTC, wtogami requested changes

2022-07-02 08:49 UTC, wtogami commented on doc/INSTALL.md
> +	        perl \
tested NACK - see notes below

2022-07-07 06:09 UTC, NicolaLS commented
> 

Oh ok, I don't know if this is easy reproducible I tried a lot of things which I can't remember so maybe something else fixed it (but I really don't think so). Would it be sufficient to just de-install perl, try again and post the ./configure output ?

2022-07-07 06:44 UTC, NicolaLS commented
Ok, so I now uninstalled lightningd and perl and did the build process again and everything worked just fine..really weird because adding perl was really the "last action" that fixed it last time.

2022-07-07 06:44 UTC, closed without merging