funder whitelist first pass
ElementsProject/lightning pull request #5566
Opened 2022-09-02 14:53 UTC by chrisguida

2022-10-25 13:27 UTC, cdecker requested changes
Thanks @chrisguida for the change. I like it, but the PR has a lot of whitespace and formatting changes, that obscure where the actual changes are. Since this increases chances of conflicts, and overlooking things in the review.

Please remove the formatting changes and resubmit :-)

2022-10-25 13:27 UTC, cdecker commented on plugins/funder.c
> +	{
Not compatible with our syntax conventions (newlines only for methods).

2022-10-25 13:27 UTC, cdecker commented on plugins/funder.c
> +new_channel_open(const tal_t *ctx, struct plugin *p, const struct node_id id,
Formatting change only?

2022-10-25 13:27 UTC, cdecker commented on plugins/funder.c
> +					     struct pending_open *open)
Formatting change only?

2022-10-25 13:27 UTC, cdecker commented on plugins/funder.c
> +		   json_tok_full_len(result), json_tok_full(buf, result));
Formatting change only?

2022-10-25 13:27 UTC, cdecker commented on plugins/funder.c
> +				    unreserve_done, unreserve_done, open);
Formatting change only?

2022-10-25 14:32 UTC, chrisguida commented
> Thanks @chrisguida for the change. I like it, but the PR has a lot of whitespace and formatting changes, that obscure where the actual changes are. Since this increases chances of conflicts, and overlooking things in the review.
> 
> Please remove the formatting changes and resubmit :-)

Yes, apologies for all the formatting changes, I have a default formatter that is very opinionated. I'll be sure to remove them once this is out of draft. Does the CLN team have a formatting settings file for vscode by any chance?

2022-11-03 22:28 UTC, niftynei commented
> Does the CLN team have a formatting settings file for vscode by any chance?

Not that I know of, good question for the discord/telegram/irc though.

2024-06-28 05:44 UTC, ShahanaFarooqui commented
Closing Draft PRs inactive for more than a year. Please feel free to reopen if required.

2024-06-28 05:44 UTC, closed without merging