Track coinbases in wallet
ElementsProject/lightning pull request #5664
Opened 2022-10-17 19:23 UTC by niftynei

Mark outputs as coinbases; don't spend them until they're mature. 

Fixes #5564

2022-10-20 03:02 UTC, rustyrussell requested changes

2022-10-20 03:02 UTC, rustyrussell commented on wallet/wallet.c
> +	if (utxo->is_in_coinbase) {
Perhaps a helper "u32 utxo_is_immature(utxo, blockheight)"?  Returns 0 if it's mature, otherwise number of blocks until it will me?

2022-10-20 03:02 UTC, rustyrussell commented on wallet/walletrpc.c
> +			json_add_string(response, "status", "confirmed");
And use helper here...

2022-10-20 03:02 UTC, rustyrussell commented on wallet/walletrpc.c
> +	wallet_extract_owned_outputs(ld->wallet, sending->wtx, 1, NULL, &change);
Exactly.

2022-11-08 20:23 UTC, vincenzopalazzo reviewed
ACK https://github.com/ElementsProject/lightning/pull/5664/commits/f9280cc1efd41ed688c29576e583ed77c8495bd1

Sorry for delay here but I only got the meaning of this while reading this issue https://github.com/ElementsProject/lightning/issues/5696

2022-11-08 20:23 UTC, vincenzopalazzo approved these changes

2022-11-09 10:55 UTC, merged