db: Backfill missing HTLC IDs in the forwards table
ElementsProject/lightning pull request #5737
Opened 2022-11-24 17:08 UTC by cdecker

We have a primary key that is spanning the `in_channel_id` and the `in_htcl_id`. The latter gets set to NULL when the HTLC and channel gets deleted, so we coalesce with a random large number that is unlikely to collide for the primary key.

2022-11-24 17:18 UTC, cdecker commented
Tested this locally against sqlite3 and postgres, and it seems to work fine.

For reference the longer cleanup would involve:

 - Recreating `forwards` without the primary key (potentially replaced with an `INDEX` if we notice that the query is slow)
 - Copy over the contents of `forwards` and then renaming the table again
 - Setting any `in_htlc_id` with a negative value to `NULL`

2022-11-24 18:18 UTC, vincenzopalazzo approved these changes
ACK https://github.com/ElementsProject/lightning/pull/5737/commits/9f791c641f8d19859549700c092ca73cd740655d

Ok, I got the point here and I agree with removing the primary key in the future, it is confusing if it is not used!

2022-11-24 18:18 UTC, vincenzopalazzo commented on wallet/db.c
>      {SQL("INSERT INTO forwards SELECT"
Putting here just a FIXME with your reason? I think I will take on this task after the release!

2022-11-24 21:24 UTC, rustyrussell commented
Oh, that's nasty!

But neater! We should *not* change the primary keys and add an index: that's horrible! This missing data only applies to old entries anyway (which is *why* I changed this table!)

2022-11-24 21:26 UTC, rustyrussell commented
Ack https://github.com/ElementsProject/lightning/commit/9f791c641f8d19859549700c092ca73cd740655d

2022-11-24 23:22 UTC, rustyrussell commented
Not sure that zeroconfrouting would pass this, though, as forward times will not be unique enough.

We might really need the uglier solution?

2022-11-25 00:51 UTC, rustyrussell requested changes
See my comment on rowid/ctid

2022-11-25 02:51 UTC, rustyrussell commented
... it works!

Pushed as fixup to test CI, squash (and fix commit msg!) if you approve.

2022-11-25 15:43 UTC, cdecker commented
I had to adjust the last commit once more: `CTID` is a tuple of block and sector (sounds disky ^^), and we need to have a `u64` in that position, so we combine the two `u32` numbers by shifting and ORing. Anyway, the expression is quite ugly but guaranteed to be unique across the entire table.

2022-11-28 13:47 UTC, merged