Autoclean fixes and docs
ElementsProject/lightning pull request #5775
Opened 2022-12-05 04:33 UTC by rustyrussell

2022-12-05 12:11 UTC, cdecker requested changes
Missing a doc markdown file, but otherwise gtg :-)

2022-12-05 12:11 UTC, cdecker commented on doc/index.rst
> +   lightning-autoclean-once <lightning-autoclean-once.7.md>
Looks like this file is missing.

2022-12-05 20:02 UTC, rustyrussell commented on doc/index.rst
> +   lightning-autoclean-once <lightning-autoclean-once.7.md>
Doh!!!

2022-12-06 09:42 UTC, cdecker commented
ACK https://github.com/ElementsProject/lightning/pull/5775/commits/492d99bb26347e283cd2443cbdb0cc6ec0a07e96

2022-12-06 09:42 UTC, merged