Bugfix: Fix 'extreme cases' logging of many commit timer failures
ElementsProject/lightning pull request #5881
Opened 2023-01-06 17:07 UTC by instagibbs

Currently it is impossible for the log line to be hit since the value is set to 1, then reset immediately after to 0. Makes it hard to see if this is happening in a degenerate way.

2023-01-09 12:33 UTC, SimonVrouwe commented
What is this about?
What problem or bug are you trying to solve?
Please add more context.

2023-01-09 14:20 UTC, instagibbs commented
I'm fixing dead code.

This log appears to be a sanity check which will show up whenever a commitment timer is set before it has received the corresponding revoke and ack for the previous commitment, which isn't allowed by the protocol.

Currently it's impossible to actually trigger because of the bug as described.

2023-01-11 05:38 UTC, rustyrussell approved these changes
Ack 7cfbaf6973f7a9e741b531a0dedb167454cdcf07

2023-01-12 11:09 UTC, vincenzopalazzo approved these changes
ACK https://github.com/ElementsProject/lightning/pull/5881/commits/7cfbaf6973f7a9e741b531a0dedb167454cdcf07

2023-02-07 00:16 UTC, rustyrussell requested changes
Needs to initialize commit_timer_attempts at start time:

```
Valgrind error file: valgrind-errors.74244
==74244== Conditional jump or move depends on uninitialised value(s)
==74244==    at 0x110AF6: send_commit (channeld.c:1239)
==74244==    by 0x13A03F: timer_expired (timeout.c:62)
==74244==    by 0x117ED3: main (channeld.c:4042)
==74244== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:send_commit
   fun:timer_expired
   fun:main
}
```

2023-02-07 01:05 UTC, instagibbs commented
good catch valgrind; fixed

2023-02-07 08:43 UTC, vincenzopalazzo approved these changes
ACK https://github.com/ElementsProject/lightning/pull/5881/commits/a2245878df75bf461842a6a4ba9c5711d48ab47c

2023-02-07 21:07 UTC, rustyrussell approved these changes

2023-02-07 21:08 UTC, merged