msggen: Enable `SendCustomMsg`
ElementsProject/lightning pull request #5978
Opened 2023-02-08 17:08 UTC by dongcarl

All the schemas are available for `SendCustomMsg` but it was never enabled in `contrib/msggen/msggen/utils/utils.py`

1. Enable it
2. Regenerate

2023-02-08 17:57 UTC, cdecker commented
ACK 4538716f0437ef4b05c64271a12d21b7d5b66346

2023-02-09 01:59 UTC, rustyrussell requested changes

2023-02-09 01:59 UTC, rustyrussell commented on doc/schemas/sendcustommsg.request.json
> +      "added": "v23.02"
These args were not added, the entire command was, so "added" should really go there.

(We don't use this info yet, but we will!)

And it was added back in v0.10.1.  I'll fix...

2023-02-09 02:01 UTC, rustyrussell approved these changes

2023-02-09 05:10 UTC, endothermicdev commented
ACK fb5dbc85a8c88a0c3d5404f2a1d84224ed4ad512

2023-02-09 05:10 UTC, merged