plugin: autoclean: cleanup the forwards with localfailed
ElementsProject/lightning pull request #6109
Opened 2023-03-21 13:24 UTC by vincenzopalazzo

While we are cleaning up the list forwards with the autoclean plugin we are not taking into count the forward's payments with the status set to `local_failed`. In this case, the forwards have no resolved time because it was not resolved by us due to some local error.

So, this commit is fixing the auto clean plugin by allowing to delete of the forwards with status set to local_failed by taking into count the received_time, with the assumption that the received_time, in this case, is equal to the resolved time (?)

Reported-by: @denis2342
Link: https://github.com/ElementsProject/lightning/issues/6058
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>
Changelog-Fixed: plugin: autoclean: considerer the forwards with status set to `local_failed`.

Fixes https://github.com/ElementsProject/lightning/issues/6058

2023-03-22 03:26 UTC, rustyrussell requested changes
Great catch!  I think we can make this both a bit neater and clearer though...

2023-03-22 03:26 UTC, rustyrussell commented on plugins/autoclean.c
> +		bool local_failed;
Hmm, in this case, lets do:

```
    const char *timefield = "resolved_time";

...

} else if (json_tok_streq(buf, status, "failed")) {
       subsys = FAILEDFORWARDS;
} else if (json_tok_streq(buf, status, "local_failed")) {
      subsys = FAILEDFORWARDS;
      /* There's no resolved_time for these, so use received */
     timefield = "received_time";
}...
```

2023-03-22 08:14 UTC, vincenzopalazzo commented on plugins/autoclean.c
> +		bool local_failed;
Uh, much better thanks!

2023-03-23 05:38 UTC, rustyrussell approved these changes
Ack 4d5300c971f3b09e35c8c9a7345e24bc0af0aec7

2023-03-23 08:18 UTC, merged