doc: add a nice explainer about how to update PR branches
ElementsProject/lightning pull request #6252
Opened 2023-05-12 00:22 UTC by niftynei

This is good info to have, that I often forget and have to spend time looking for. It'd be nice to have it documented in the project somewhere so people new the project (or new to maintaining maybe?) know where to find it.

Open to suggestions of other places to put this; totally understandable if it's not useful to have in this repo, particularly.

2023-05-19 12:42 UTC, cdecker commented
Rebased on top of `master`

2023-05-24 10:36 UTC, vincenzopalazzo approved these changes
ACK https://github.com/ElementsProject/lightning/pull/6252/commits/e0540b516e3247601a2ef324d738ce49bd003e53

But I had a comment; it is not a blocking one because git has a lot of different ways to do the same things, and I may misunderstood how to use your suggestion

2023-07-21 05:43 UTC, rustyrussell commented
This is easier with the github cmdline tools BTW!

But it needs moving to the updated docs...

2023-07-24 04:30 UTC, niftynei commented
> This is easier with the github cmdline tools BTW!

Hmm. Do most people install those? I can add a second entry with info about it.

2023-07-24 10:59 UTC, vincenzopalazzo commented
>Hmm. Do most people install those? 

I never use it but I guess a common things for people that are  new to git, looks like a good twitter pool :)

2023-07-28 00:21 UTC, rustyrussell requested changes

2023-07-28 00:21 UTC, rustyrussell commented on doc/HACKING.md
> +	git checkout pr/<pr#>
I think this needs the .github/config magic of:

```
[remote "origin"]
    fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```

2023-07-28 00:23 UTC, rustyrussell commented
Note: doc moved and updated in doc/contribute-to-core-lightning/contributor-workflow.md

2023-07-31 18:42 UTC, niftynei commented on doc/HACKING.md
> +	git checkout pr/<pr#>
ah yeah, i'll add that!

2023-10-26 21:18 UTC, nepet commented
Removed the milestone as this PR seems to be stuck.

2023-12-05 07:41 UTC, niftynei commented
Added requested comment about the `pr/#` folder and moved to new docs location.

2024-01-16 17:45 UTC, cdecker commented
I rebased this on top of `master`, which was a bit complicated since there was a rename of the file inbetween. Sorry for dropping your authorship @niftynei but I couldn't think of a simpler way than to hard reset and reapply your diff on the new filename instead.

This will be merged as soon as the CI passes :fireworks:

2024-01-16 18:00 UTC, merged