doc: add tip on extracting binary release
ElementsProject/lightning pull request #6633
Opened 2023-08-29 12:15 UTC by maxwedwards

How and where to extract the binaries has come up on Discord at least a couple of times. Hopefully this tip will help.

2023-08-29 12:21 UTC, vincenzopalazzo approved these changes
Make sense!

ACK https://github.com/ElementsProject/lightning/pull/6633/commits/a7e0c2d6de3cf6b6f9fcc2e9173b97a360c3ba0e

2023-08-31 05:17 UTC, rustyrussell requested changes

2023-08-31 05:17 UTC, rustyrussell commented on doc/getting-started/getting-started/installation.md
> +sudo tar -xvf <release>.tar.xz -C /usr/local --strip-components=2
```
sudo tar -xvaf <release>.tar.xz -C /usr/local --strip-components=2
```

Without the `a` it won't work...

2023-08-31 05:18 UTC, rustyrussell commented on doc/getting-started/getting-started/installation.md
> +sudo tar -xvf <release>.tar.xz -C /usr/local --strip-components=2
Wait, it does... what wild magic is this?!!

2023-08-31 05:23 UTC, rustyrussell commented on doc/getting-started/getting-started/installation.md
> +sudo tar -xvf <release>.tar.xz -C /usr/local --strip-components=2
TIL!  Man page is silent, but info page:

```
   Reading compressed archive is even simpler: you don't need to specify
any additional options as GNU 'tar' recognizes its format automatically.
Thus, the following commands will list and extract the archive created
in previous example:

     # List the compressed archive
     $ tar tf archive.tar.gz
     # Extract the compressed archive
     $ tar xf archive.tar.gz

   The format recognition algorithm is based on "signatures", a special
byte sequences in the beginning of file, that are specific for certain
compression formats.  If this approach fails, 'tar' falls back to using
archive name suffix to determine its format (*note auto-compress::, for
a list of recognized suffixes).
```

2023-08-31 05:23 UTC, rustyrussell approved these changes

2023-08-31 06:43 UTC, merged