cln-grpc: do not generate cerficates when no autostart.
ElementsProject/lightning pull request #6755
Opened 2023-10-10 09:04 UTC by tonyaldon

When we don't set `grpc-port` option, the `cln-grpc` plugin is not started.  So, we shouldn't generate certificates in that case.

2023-10-10 09:42 UTC, cdecker approved these changes
ACK https://github.com/ElementsProject/lightning/pull/6755/commits/87fb39a3abf8894bcf12f3ab2ba26260a0f61d27

2023-10-12 18:41 UTC, vincenzopalazzo requested changes
I think it is missing just some python-format changes and we are good

2023-10-12 18:41 UTC, vincenzopalazzo commented on tests/test_cln_rs.py
> +    pem_files = [f for f in files if re.match(r".*\.pem$",f)]
```suggestion
    pem_files = [f for f in files if re.match(r".*\.pem$", f)]
```

This cause the following error

```
2023-10-10T09:08:00.8610981Z checking for ANSI C header files... yes
2023-10-10T09:08:00.9901583Z checking for sys/types.h... yes
2023-10-10T09:08:01.1104640Z checking for sys/stat.h... tests/test_cln_rs.py:190:58: E231 missing whitespace after ','
2023-10-10T09:08:01.1687731Z yes
2023-10-10T09:08:01.1774097Z make: *** [Makefile:538: check-python-flake8] Error 1
2023-10-10T09:08:01.1774740Z make: *** Waiting for unfinished jobs....
2023-10-10T09:08:01.3928110Z checking for stdlib.h... yes
2023-10-10T09:08:01.6206722Z checking for string.h... yes
```

2023-10-13 06:04 UTC, tonyaldon commented
Thanks @vincenzopalazzo for helping me with my first PRs in CLN and showing me exactly what to change.

I also started to look at the CI logs to find the errors by myself (but maybe better not doing them in the first place).

This is the second time this week I haven't checked Python flake8 before opening a PR.  I'll try not to do that mistake in future.

2023-10-13 07:21 UTC, vincenzopalazzo commented
>This is the second time this week I haven't checked Python flake8 before opening a PR. I'll try not to do that mistake in future.

No problem the review are here for this :) I find always Python formatting is a little bit strange :)

2023-10-13 07:22 UTC, vincenzopalazzo approved these changes
ACK https://github.com/ElementsProject/lightning/pull/6755/commits/00a60a3608210de7e6dc1c4f73b03634a668f5dd

2023-10-13 08:25 UTC, merged