splice: Reestablish when commit or sig sends fail
ElementsProject/lightning pull request #6840
Opened 2023-11-03 03:39 UTC by ddustin

Adds tests for when the connection fails during
1) splice tx_signature
2) splice commitment_signed

Fleshed out the reestablish flow for these two cases and implemented the fixes to make these reestablish flows work.

Changelog-Fixed: Implemented splicing restart logic for tx_signature and commitment_signed.

2023-11-03 10:47 UTC, vincenzopalazzo reviewed
Looks like that test are failing

```
test_splice passed 1 out of the required 1 times. Success!

===End Flaky Test Report===
=========================== short test summary info ============================
FAILED tests/test_opening.py::test_rbf_reconnect_tx_construct - TimeoutError: Unable to find "[re.compile('dualopend daemon died before signed PSBT returned')]" in logs.
FAILED tests/test_splicing_disconnect.py::test_splice_disconnect_sig - TimeoutError: Unable to find "[re.compile('CHANNELD_AWAITING_SPLICE to CHANNELD_NORMAL')]" in logs.
===== 2 failed, 105 passed, 582 skipped, 33 warnings in 699.05s (0:11:39) ======
```

2023-11-11 11:13 UTC, vincenzopalazzo approved these changes
ACK https://github.com/ElementsProject/lightning/pull/6840/commits/50bcd8932006dfb9ba3a53016b5109a06754bea6

2023-11-14 02:37 UTC, rustyrussell requested changes
I'm going to accept this since we're close to release and it only effects experimental.  However, it's a giant blob of unreviewable changes, which is not nice :(

At least one thing is wrong, though.

2023-11-14 02:37 UTC, rustyrussell commented on channeld/channeld.c
> +				       enum peer_wire third_allowed_type)
You never check third_allowed_type?

2023-11-15 18:20 UTC, vincenzopalazzo commented
This is introducing breaking change so @nepet drop for the milestone, it is breaking VLS with https://github.com/ElementsProject/lightning/issues/6870 so we should drop it from the current release IMHO too

2023-11-17 20:15 UTC, ksedgwic approved these changes
Investigated the "commitment mismatch" VLS was seeing with `tests/test_splicing_disconnect.py::test_splice_disconnect_commit`, looks like this is not a bug and we can easily handle in VLS: https://gitlab.com/lightning-signer/vls-hsmd/-/merge_requests/132#note_1654982750

This PR looks good from VLS

2023-11-19 16:44 UTC, nepet commented
Squashed fixup commit

2023-11-19 23:04 UTC, rustyrussell commented
Ack https://github.com/ElementsProject/lightning/commit/b54af9f8f4e24685a368bb5185aa068fbd573d6d

2023-11-20 03:56 UTC, niftynei approved these changes
Bunch of nits, but nothing major. Nice job getting this turned around so quickly.

More tests would be nice??

2023-11-20 03:56 UTC, niftynei commented on channeld/channeld.c
> +				      bool recv_commitments,
nit: maybe call this 'expect_rcv_commitments'?

2023-11-20 03:56 UTC, niftynei commented on channeld/channeld.c
> +		if (inflight->last_tx != their_commit->tx)
in what cases would these not be the same?

2023-11-20 03:56 UTC, niftynei commented on channeld/channeld.c
> +		send_channel_update(peer, true);
can we get rid of this? what's it for here?

2023-11-20 03:56 UTC, niftynei commented on channeld/channeld.c
> +	resume_splice_negotiation(peer, true, true, true, true);
nit: could you compact these args into a bitfield/enum?

2023-11-20 03:56 UTC, niftynei commented on channeld/channeld.c
> +static const u8 *peer_expect_msg_three(const tal_t *ctx,
nit: switch statement?

2023-11-20 03:56 UTC, niftynei commented on tests/test_splicing_disconnect.py
> +    funds_result = l1.rpc.fundpsbt("109000sat", "slow", 166, excess_as_change=True)
wen splice cmd?? :eyes:

2023-11-20 03:56 UTC, niftynei commented on tests/test_splicing_disconnect.py
> +    l1.start()
you could also just call `connect` again?

2023-11-20 03:56 UTC, niftynei commented on tests/test_splicing_disconnect.py
> +    # Check that the splice doesn't generate a unilateral close transaction
is there another signal we can check for?

2023-11-20 03:56 UTC, niftynei commented on tests/test_splicing_disconnect.py
> +    print("l1 splice_update")
can we get rid of the prints? :grin:

2023-11-20 03:56 UTC, niftynei commented on tests/test_splicing_disconnect.py
> +    print("Killing l2 without sending WIRE_COMMITMENT_SIGNED")
nit: assert we're in the state expected before killing + reconnecting

2023-11-20 03:56 UTC, niftynei commented on tests/test_splicing_disconnect.py
> +    assert l1.db_query("SELECT count(*) as c FROM channeltxs;")[0]['c'] == 0
one other test i would add tests the tx-abort pathway?

2023-11-20 06:35 UTC, merged