cln-rpc: rewrite is_none_or_empty to not use clone()
ElementsProject/lightning pull request #6868
Opened 2023-11-14 15:53 UTC by daywalker90

This should be the same, but without cloning.

2023-11-15 09:09 UTC, vincenzopalazzo requested changes

2023-11-15 09:09 UTC, vincenzopalazzo commented on cln-rpc/src/lib.rs
> +    }
```suggestion
    f.map_or(true, |value| value.is_empty())
```

I think this is a better way of writing it?

2023-11-15 09:13 UTC, daywalker90 commented
even better, yes!

2023-12-16 09:25 UTC, vincenzopalazzo approved these changes
ACK https://github.com/ElementsProject/lightning/pull/6868/commits/413945a47562794edafc1a0fa132fe05e7b467e6

2023-12-16 09:32 UTC, vincenzopalazzo approved these changes
Ok I took the freedom to fix the git history and rebased it.

This should not create CI failure, but lets wait

ACK https://github.com/ElementsProject/lightning/pull/6868/commits/5f19a889235793b685c5d61d5f2fb9d113ac31d9

2023-12-16 10:26 UTC, vincenzopalazzo approved these changes
Ok I was wrong because with the `f.map` take the ownership.

So better use `as_ref()` to fix the following error

```
➜  lightning git:(pr6868) ✗ cargo build
   Compiling cln-rpc v0.1.7 (/home/vincent/github/work/lightning/cln-rpc)
error[E0507]: cannot move out of `*f` which is behind a shared reference
    --> cln-rpc/src/lib.rs:133:5
     |
133  |     f.map_or(true, |value| value.is_empty())
     |     ^ -------------------------------------- `*f` moved due to this method call
     |     |
     |     help: consider calling `.as_ref()` or `.as_mut()` to borrow the type's contents
     |     move occurs because `*f` has type `std::option::Option<Vec<T>>`, which does not implement the `Copy` trait
     |
note: `std::option::Option::<T>::map_or` takes ownership of the receiver `self`, which moves `*f`
    --> /home/vincent/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1129:25
     |
1129 |     pub fn map_or<U, F>(self, default: U, f: F) -> U
     |                         ^^^^
help: you can `clone` the value and consume it, but this might not be your desired behavior
     |
133  |     f.clone().map_or(true, |value| value.is_empty())
     |      ++++++++

For more information about this error, try `rustc --explain E0507`.
```

Now we are good 

ACK https://github.com/ElementsProject/lightning/pull/6868/commits/f6f296b940afc92e09c7226509b0851d0f82acc4

2023-12-16 11:11 UTC, merged