Custom msg as notification
ElementsProject/lightning pull request #6899
Opened 2023-11-27 13:51 UTC by ErikDeSmedt

Implements notifications for `custommsg`

2023-11-27 15:33 UTC, ErikDeSmedt commented
Marked as draft because I am getting a valgrind error locally

```
------------------------------- Valgrind errors --------------------------------
Valgrind error file: valgrind-errors.154915
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x153C25: main (lightningd.c:978)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B77B3: trace_span_slot (trace.c:78)
==154915==    by 0x1B7A9F: trace_span_start (trace.c:140)
==154915==    by 0x153C25: main (lightningd.c:978)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_slot
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B77BE: trace_span_slot (trace.c:83)
==154915==    by 0x1B7A9F: trace_span_start (trace.c:140)
==154915==    by 0x153C25: main (lightningd.c:978)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_slot
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x153DA2: main (lightningd.c:1081)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B77B3: trace_span_slot (trace.c:78)
==154915==    by 0x1B7A9F: trace_span_start (trace.c:140)
==154915==    by 0x153DA2: main (lightningd.c:1081)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_slot
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B77BE: trace_span_slot (trace.c:83)
==154915==    by 0x1B7A9F: trace_span_start (trace.c:140)
==154915==    by 0x153DA2: main (lightningd.c:1081)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_slot
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x153DE9: main (lightningd.c:1106)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x153E0D: main (lightningd.c:1118)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x153E42: main (lightningd.c:1132)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x18F03C: wallet_new (wallet.c:114)
==154915==    by 0x153E51: main (lightningd.c:1133)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:wallet_new
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B77B3: trace_span_slot (trace.c:78)
==154915==    by 0x1B7A9F: trace_span_start (trace.c:140)
==154915==    by 0x18F03C: wallet_new (wallet.c:114)
==154915==    by 0x153E51: main (lightningd.c:1133)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_slot
   fun:trace_span_start
   fun:wallet_new
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B77BE: trace_span_slot (trace.c:83)
==154915==    by 0x1B7A9F: trace_span_start (trace.c:140)
==154915==    by 0x18F03C: wallet_new (wallet.c:114)
==154915==    by 0x153E51: main (lightningd.c:1133)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_slot
   fun:trace_span_start
   fun:wallet_new
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x18F079: wallet_new (wallet.c:120)
==154915==    by 0x153E51: main (lightningd.c:1133)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:wallet_new
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x18F0A0: wallet_new (wallet.c:124)
==154915==    by 0x153E51: main (lightningd.c:1133)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:wallet_new
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x18F0C9: wallet_new (wallet.c:128)
==154915==    by 0x153E51: main (lightningd.c:1133)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:wallet_new
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x153EB0: main (lightningd.c:1156)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x153F01: main (lightningd.c:1176)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x153FDF: main (lightningd.c:1207)
==154915== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:trace_span_find
   fun:trace_span_start
   fun:main
}
==154915== Conditional jump or move depends on uninitialised value(s)
==154915==    at 0x1B7795: trace_span_find (trace.c:67)
==154915==    by 0x1B7A91: trace_span_start (trace.c:139)
==154915==    by 0x12F112: bitcoind_getrawblockbyheight_ (bitcoind.c:515)
==154915==    by 0x1304B2: check_chain (chaintopology.c:1307)
==154915==    by 0x12EAAE: getchaininfo_callback (bitcoind.c:572)
==154915==    by 0x176AED: plugin_response_handle (plugin.c:660)
==154915==    by 0x179FFA: plugin_read_json_one (plugin.c:772)
==154915==    by 0x17A296: plugin_read_json (plugin.c:823)
==154915==    by 0x3115 [...]

2023-12-14 13:42 UTC, ErikDeSmedt commented
Some conflict appeared. I've rebased the branch so it can be merged more easily.

2023-12-14 23:57 UTC, rustyrussell approved these changes
Ack 43903936ffe06b9cd84235bccbeb23780aff7112a

Looks good!

2023-12-14 23:58 UTC, rustyrussell requested changes
The first commit needs a "Changelog-Added: Plugins: notification `custommsg` for receiving an unknown protocol message" line  (we used to have a bot to enforce this, but it's broken).

2023-12-16 01:06 UTC, rustyrussell approved these changes

2023-12-16 01:06 UTC, merged