Splice: Complete tx_abort implementation
ElementsProject/lightning pull request #6940
Opened 2023-12-13 20:44 UTC by ddustin

2023-12-15 18:40 UTC, ksedgwic commented
@ddustin should we try this out (integration tests) w/ our splicing branch?  Our branch is not quite released yet, but is close ...

2023-12-15 19:09 UTC, ddustin commented
> @ddustin should we try this out (integration tests) w/ our splicing branch?  Our branch is not quite released yet, but is close ...

It's not quite ready for testing yet

2023-12-16 18:53 UTC, ksedgwic commented
@devrandom review beg

2023-12-18 20:29 UTC, ksedgwic commented
@ddustin I think I'm making some assumptions, want to make sure they are correct:
- `tx_abort` is used to cancel a in-progress interactive splice tx negotiation
- the semantics are the same as dual-funding

I found the dual-funding docs and 5 comments on https://github.com/lightning/bolts/pull/863, is there anything additional I should be looking at?

2023-12-19 16:02 UTC, ddustin commented
> @ddustin I think I'm making some assumptions, want to make sure they are correct:
> 
> - `tx_abort` is used to cancel a in-progress interactive splice tx negotiation
> 
> - the semantics are the same as dual-funding
> 
> 
> 
> I found the dual-funding docs and 5 comments on https://github.com/lightning/bolts/pull/863, is there anything additional I should be looking at?

The spec for `tx_abort` is in dual and it's essentially the same -- though the implementation for splice abort is in channeld.c while dual's abort is in dualopend.c

2024-01-31 12:05 UTC, cdecker commented
Hi @ddustin, just going through all the open PRs that may make it into v24.02, and this one looks good for inclusion as far as I can see. Can you share your view on the current status, and whether we can include it or not? If included, we may do 1-2 rounds of final reviews and merge it, otherwise I'll untag it for the milestone, until it is ready for inclusion ^^

2024-01-31 22:16 UTC, ddustin commented
> Hi @ddustin, just going through all the open PRs that may make it into v24.02, and this one looks good for inclusion as far as I can see. Can you share your view on the current status, and whether we can include it or not? If included, we may do 1-2 rounds of final reviews and merge it, otherwise I'll untag it for the milestone, until it is ready for inclusion ^^

Hi @cdecker, it would be great to get this included in the next release! I believe it is definitely ready for inclusion.

This should all only apply under the experimental-splicing flag making it a safer change.

In some manual tests aggressively restarting channeld (which tx_abort does) reveals some passed file descriptor issues. I believe this is revealing an existing issue and not related to this PR.

If correct this should enable us to add flaky fd passing to the CI. To build the test however I need PR #6980 merged too as the test is dependent on both.

2024-02-01 10:58 UTC, cdecker commented
Ok, got it. I quite like #6980, but the discussion doesn't look finished yet. Am I good to take on this PR and shepherd it through CI, even if #6980 may not make it through in this release? The next release would be 24.05, so not a huge delay, but I prefer pulling in as much as possible to keep a clean worktable.

2024-02-01 21:13 UTC, ddustin commented
> Ok, got it. I quite like #6980, but the discussion doesn't look finished yet. Am I good to take on this PR and shepherd it through CI, even if #6980 may not make it through in this release? The next release would be 24.05, so not a huge delay, but I prefer pulling in as much as possible to keep a clean worktable.

Yeah that works 👍, thanks!

2024-02-09 05:06 UTC, rustyrussell requested changes
Trivial changes mainly.


But last commit should be the first: that means tests always pass!

2024-02-09 05:06 UTC, rustyrussell commented on lightningd/channel_control.c
> +	else {
Weird linebreak

2024-02-09 05:06 UTC, rustyrussell commented on channeld/channeld.c
> +static struct inflight *last_inflight(struct peer *peer)
const struct peer *

2024-02-09 05:06 UTC, rustyrussell commented on channeld/channeld.c
> +static size_t last_inflight_index(struct peer *peer)
here too...

2024-02-09 05:06 UTC, rustyrussell commented on channeld/channeld.c
> +				      struct bitcoin_outpoint *funding)
Both of these can be const...

2024-02-09 05:06 UTC, rustyrussell commented on channeld/channeld.c
> +	for (i = 0; i < inflight->psbt->num_inputs; i++) {
for (size_t i.... since you don't use the i var outside the loop?

2024-02-09 05:06 UTC, rustyrussell commented on channeld/channeld.c
> +	if (!msg || fromwire_peektype(msg) != WIRE_TX_ABORT)
FWIW, fromwire_peektype returns -1 on NULL, so it's safe.

2024-02-09 17:08 UTC, cdecker commented
I tried rebasing this PR, but managed to somehow break it. It now has an undefined symbol `towire_connectd_peer_final_msg` and I can't find a trace of that message anywhere.

2024-02-10 18:05 UTC, ddustin commented
> I tried rebasing this PR, but managed to somehow break it. It now has an undefined symbol `towire_connectd_peer_final_msg` and I can't find a trace of that message anywhere.

Ah looks like commit db6f0da3b349d89892e8d96012c3ab184735593b removed that routine. Should be a simple update to use the new method.

2024-02-10 18:13 UTC, ddustin commented
> Trivial changes mainly.
> 
> But last commit should be the first: that means tests always pass!

Thanks for the review!

I addressed these changes, rebased master, and updated it to work with the latest master.

@cdecker once it passes CI it should be good to go

2024-02-11 09:46 UTC, merged