tests: augment test to check to_remote witness generation
ElementsProject/lightning pull request #6992
Opened 2024-01-13 22:10 UTC by ksedgwic

Changelog-Added: added a withdraw all to the end of test_onchain_their_unilateral_out to ensure that the unilateral close info is correct with anchors.

Tests https://github.com/Blockstream/greenlight/issues/348

2024-01-14 12:03 UTC, vincenzopalazzo requested changes

2024-01-14 12:03 UTC, vincenzopalazzo commented on tests/test_closing.py
>  def test_listfunds_after_their_unilateral(node_factory, bitcoind):
Some small python checking error

```
checking for fcntl... yes
checking whether strnlen is declared... tests/test_closing.py:2426:1: E302 expected 2 blank lines, found 1
yes
make: *** [Makefile:538: check-python-flake8] Error 1
make: *** Waiting for unfinished jobs....
```

Should be fixed with 

```suggestion
    # Have l1 send all funds to check that the unilateral close info is correct
    l1.rpc.withdraw(l1.rpc.newaddr('bech32')['bech32'], 'all', minconf=0)


def test_listfunds_after_their_unilateral(node_factory, bitcoind):
```

2024-01-26 17:02 UTC, cdecker commented
Rebased on top of `master`

2024-01-26 17:05 UTC, cdecker commented
I should have waited for the rebase to complete. Looks like you unchecked the "Allow Maintainer Updates" (or similar) checkbox, so you will have to rebase it @ksedgwic

2024-01-31 14:51 UTC, merged