`cln_plugin` : Support wildcard subscriptions
ElementsProject/lightning pull request #7106
Opened 2024-02-23 10:54 UTC by ErikDeSmedt

In Core Lightning plugins can subscribe to notifications using a wildcard `*`.
When the wildcard is used the plugin will receive all notifications.

This behavior was not supported by `cln_plugin`.
The first 2 commits create a plug-in that listens to the the wildcard `*`-subscription
and test the behavior. It appears that `cln_plugin` accepts the subscription but fails when the first plug-in message
is received.

The last commit adapts the `cln_plugin`-crate to support the wildcard.

2024-02-23 10:57 UTC, ErikDeSmedt commented
This PR is also use-ful for https://github.com/ElementsProject/lightning/pull/7084.

2024-03-25 09:57 UTC, rustyrussell requested changes

2024-03-25 09:57 UTC, rustyrussell commented on tests/test_cln_rs.py
> +def test_rust_plugin_subscribe_wildcard(node_factory):
This is great, but please use `@pytest.mark.xfail(strict=True)` annotation above this, and remove it in the next commit.  That pattern means you don't break bisect, and it's clear...

2024-04-17 13:16 UTC, ErikDeSmedt commented
I think the issues addressed by @rustyrussell have been fixed.
@endothermicdev: Could you merge this one cause it blocks https://github.com/ElementsProject/lightning/pull/7084

2024-04-30 20:15 UTC, cdecker approved these changes
ACK e32e654e1c76a2149a617dea43fe38c6d977e077

2024-04-30 20:24 UTC, merged