Clarify listpeerchannels documentation.
ElementsProject/lightning pull request #7155
Opened 2024-03-17 18:36 UTC by evansmj

This is to clarify the listpeerchannels documentation.  I had been reading it as though listpeerchannels returns all channels in the network, which while developing a frontend did not make sense so I spent time testing in startup_regtest.sh to figure out what it really does.  I think this clarification would help others in the future.

2024-03-19 00:29 UTC, evansmj commented
Wait until https://github.com/ElementsProject/lightning/pull/6995 is merged

2024-03-19 09:27 UTC, vincenzopalazzo requested changes

2024-03-19 09:27 UTC, vincenzopalazzo commented on doc/lightning-listpeerchannels.7.md
> +The **listpeerchannels** RPC command returns data on this node's channels, with the possibility to filter the channels by the id of a remote node.
idk if this is clear, maybe it is. However, listpeerchannels return the list of channels inside the network divided by peers.

e.g: 
peer -> channels
peer -> channels

2024-05-21 19:51 UTC, ShahanaFarooqui commented
Closing in favour of PR #7326.

2024-05-21 19:51 UTC, closed without merging