trace payment_continue and payment mods
ElementsProject/lightning pull request #7556
Opened 2024-08-12 08:42 UTC by JssDWt

2024-08-15 11:30 UTC, cdecker commented
Thanks @JssDWt, I've been wanting to instrument this part of the code for quite a while, and never had the muse to get started. I added #7575 on top of your change to instrument all JSON-RPC calls that plugins start, and we can likely also instrument all entrypoints to the plugin as well (rpcmethod, hook and notifications).

2024-08-16 07:50 UTC, cdecker requested changes

2024-08-16 07:50 UTC, cdecker commented on plugins/libplugin-pay.c
> +		char str[2];
We generally don't allow the use of `sprintf` as it isn't safe (it takes a buffer it doesn't know the size of). Please switch this to `snprintf` which errors out if the buffer is too small for the format. Or better `tal_fmt(tmpctx, "%d", num);` will do all of it at once, including fixing the buffer overflow should we ever have 100+ modifiers 😋

2024-08-16 08:34 UTC, JssDWt commented on plugins/libplugin-pay.c
> +		char str[2];
I saw you already corrected that in #7575.
Should I fix that in this commit? Or close this PR and go with your PR there?

2024-08-16 09:01 UTC, cdecker commented on plugins/libplugin-pay.c
> +		char str[2];
However we want to merge them. We can merge #7575 and your commit should still be credited to you 🤗 Or we fix up this one, merge this and then my follow-up PR.

By the way, if you check the allow maintainer checkbox when opening a PR you allow us to amend, fix up and fine tune PRs in situ 😉

2024-08-16 11:10 UTC, JssDWt commented
@cdecker I moved the commits around a little bit. Only tracing payment_continue now, because under some circumstances it seemed that the traces got intertwined. Also incorporated your suggestion [here](https://github.com/ElementsProject/lightning/pull/7556#discussion_r1719490112)

2024-08-16 11:10 UTC, JssDWt commented on plugins/libplugin-pay.c
> +		char str[2];
Fixed it up in this one. Although this one includes your commit now :-S

2024-10-31 13:59 UTC, JssDWt commented
Rebased. And also fixed a bug where the `error` field would be `false` when there was an error and vice versa.

2024-11-12 00:49 UTC, rustyrussell commented
Pretty!  I missed this on the milestone, fixed now.

Rebasing now.

2024-11-12 00:59 UTC, rustyrussell commented
This is confusing.  https://github.com/ElementsProject/lightning/pull/7575 says it builds on this, this says it's now based on that.  And I can't force push to this branch to rebase.

So I'm going to add to the confusion by opening another PR!

2024-11-13 12:15 UTC, closed without merging