Makefile: Next version update to 24.11
ElementsProject/lightning pull request #7646
Opened 2024-09-06 05:36 UTC by ShahanaFarooqui

Changelog-None.

2024-09-06 19:43 UTC, niftynei commented
Seems like there's an unrelated test flake

```
**BROKEN** lightningd: DEPRECATED API USED rest-port.clnrest-prefix 
lightningd-1 2024-09-06T17:34:34.298Z UNUSUAL lightningd: Option rest-port=36301 deprecated in v23.11, renaming to clnrest-port=36301
lightningd-1 2024-09-06T17:34:34.298Z **BROKEN** lightningd: DEPRECATED API USED rest-host.clnrest-prefix 
lightningd-1 2024-09-06T17:34:34.298Z UNUSUAL lightningd: Option rest-host=127.0.0.1 deprecated in v23.11, renaming to clnrest-host=127.0.0.1
```

2024-09-10 15:53 UTC, ShahanaFarooqui commented
@niftynei CI is fixed after adjusting some tests due to updated next cln release version.  Please review and ACK now.

2024-09-13 13:56 UTC, vincenzopalazzo requested changes

2024-09-13 13:56 UTC, vincenzopalazzo commented on .github/PULL_REQUEST_TEMPLATE.md
This looks like a change that required a separate commit

2024-09-13 13:56 UTC, vincenzopalazzo commented on doc/contribute-to-core-lightning/release-checklist.md
same for

2024-09-13 13:56 UTC, vincenzopalazzo commented on tests/test_gossip.py
removing logs to fix the CI sounds like a dangerous thing, probably the right fix is https://github.com/ElementsProject/lightning/pull/7663

2024-09-13 21:27 UTC, ShahanaFarooqui commented on .github/PULL_REQUEST_TEMPLATE.md
This template will also require to be updated after every release cycle with the next release dates (first freeze, RC1 etc). So I wanted to bundle all changes related to post release cycle in a single PR.

2024-09-13 21:29 UTC, ShahanaFarooqui commented on doc/contribute-to-core-lightning/release-checklist.md
This also is the part of "post release wrap-up and prepare for next release" cycle like above. So keeping them all together.

2024-09-13 21:42 UTC, ShahanaFarooqui commented on tests/test_gossip.py
Adjusted other failing tests to make them compatible with the next release but this test is still testing for `listchannels()['channels']]` which has been moved to `listpeerchannels` in v23.02.

2024-09-15 09:30 UTC, vincenzopalazzo commented on .github/PULL_REQUEST_TEMPLATE.md
Right, but in the same PR you can create an additional commit just for this github docs updated

2024-09-16 06:47 UTC, rustyrussell commented
I reversed the order of commits to put CI changes *first*.

2024-09-17 19:48 UTC, ShahanaFarooqui commented on .github/PULL_REQUEST_TEMPLATE.md
Thanks, Split the commit into three separate commits now.

2024-09-18 07:29 UTC, merged