add libpq for multi-arch build configuration
ElementsProject/lightning pull request #7827
Opened 2024-11-16 15:04 UTC by arowser

add libpq for multi-arch build configuration

Fix https://github.com/ElementsProject/lightning/issues/7649

depend  [7826](https://github.com/ElementsProject/lightning/pull/7826)

2024-12-06 18:12 UTC, s373nZ commented on Dockerfile
> +    wget -q https://www.sqlite.org/2019/sqlite-src-3290000.zip -O sqlite.zip \
When I tried to build on x86, just to make a sanity check, this line fails for me. Looks like it needs an `&&` to concat the commands?

2024-12-07 23:05 UTC, s373nZ requested changes
My prior comment was marked as resolved, but there were no code changes or explanation? Still seeing a build error. The rest of the PR looks like it should work, though.

Can you explain how you're testing this?

2024-12-08 08:34 UTC, arowser commented
What's your build error?
The dockerfile use to crossbuild with qemu, but the libq not exists on arm
environment, so I added the build steps for the  libq library.

On Sun, Dec 8, 2024 at 7:05 AM Se7enZ ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> My prior comment was marked as resolved, but there were no code changes or
> explanation? Still seeing a build error. The rest of the PR looks like it
> should work, though.
>
> Can you explain how you're testing this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ElementsProject/lightning/pull/7827#pullrequestreview-2486696343>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEEDCUEYVU3KRGVWWU5IO32EN5LLAVCNFSM6AAAAABR4456JGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOBWGY4TMMZUGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-08 11:32 UTC, s373nZ commented
> What's your build error? The dockerfile use to crossbuild with qemu, but the libq not exists on arm environment, so I added the build steps for the libq library.

The error is related to `wget` downloading the source code, which produces the `docker build` error:

```
 ERROR [base-builder  6/12] RUN wget -q https://zlib.net/fossils/zlib-1.2.13.tar.gz -O zlib.tar.  8.9s
------
 > [base-builder  6/12] RUN wget -q https://zlib.net/fossils/zlib-1.2.13.tar.gz -O zlib.tar.gz &&     wget -q https://www.sqlite.org/2019/sqlite-src-3290000.zip -O sqlite.zip     wget -q https://ftp.postgresql.org/pub/source/v17.1/postgresql-17.1.tar.gz -O postgres.tar.gz:
------
Dockerfile:96
--------------------
  95 |
  96 | >>> RUN wget -q https://zlib.net/fossils/zlib-1.2.13.tar.gz -O zlib.tar.gz && \
  97 | >>>     wget -q https://www.sqlite.org/2019/sqlite-src-3290000.zip -O sqlite.zip \
  98 | >>>     wget -q https://ftp.postgresql.org/pub/source/v17.1/postgresql-17.1.tar.gz -O postgres.tar.gz
  99 |
--------------------
ERROR: failed to solve: process "/bin/sh -c wget -q https://zlib.net/fossils/zlib-1.2.13.tar.gz -O zlib.tar.gz &&     wget -q https://www.sqlite.org/2019/sqlite-src-3290000.zip -O sqlite.zip     wget -q https://ftp.postgresql.org/pub/source/v17.1/postgresql-17.1.tar.gz -O postgres.tar.gz" did not complete successfully: exit code: 4
```

As I mentioned in  my initial review comment, it should be an easy fix, adding the `&&` to the end of that line. Curious how you've tested this, though, if that is breaking.

2024-12-08 11:40 UTC, s373nZ commented
Additionally, this PR needs the commit message updated to contain a `Changelog-*:` notation in the message body as described in [this documentation](https://docs.corelightning.org/docs/coding-style-guidelines#changelog-entries-in-commit-messages) to avoid the build failure here:

https://github.com/ElementsProject/lightning/actions/runs/11883516546/job/33110390750?pr=7827

2024-12-08 23:11 UTC, arowser commented
The errors have been resolved as you mention, if you have any other build
issues please let me know.

On Sun, Dec 8, 2024 at 7:32 PM Se7enZ ***@***.***> wrote:

> What's your build error? The dockerfile use to crossbuild with qemu, but
> the libq not exists on arm environment, so I added the build steps for the
> libq library.
>
> The error is related to wget downloading the source code, which produces
> the docker build error:
>
>  ERROR [base-builder  6/12] RUN wget -q https://zlib.net/fossils/zlib-1.2.13.tar.gz -O zlib.tar.  8.9s
> ------
>  > [base-builder  6/12] RUN wget -q https://zlib.net/fossils/zlib-1.2.13.tar.gz -O zlib.tar.gz &&     wget -q https://www.sqlite.org/2019/sqlite-src-3290000.zip -O sqlite.zip     wget -q https://ftp.postgresql.org/pub/source/v17.1/postgresql-17.1.tar.gz -O postgres.tar.gz:
> ------
> Dockerfile:96
> --------------------
>   95 |
>   96 | >>> RUN wget -q https://zlib.net/fossils/zlib-1.2.13.tar.gz -O zlib.tar.gz && \
>   97 | >>>     wget -q https://www.sqlite.org/2019/sqlite-src-3290000.zip -O sqlite.zip \
>   98 | >>>     wget -q https://ftp.postgresql.org/pub/source/v17.1/postgresql-17.1.tar.gz -O postgres.tar.gz
>   99 |
> --------------------
> ERROR: failed to solve: process "/bin/sh -c wget -q https://zlib.net/fossils/zlib-1.2.13.tar.gz -O zlib.tar.gz &&     wget -q https://www.sqlite.org/2019/sqlite-src-3290000.zip -O sqlite.zip     wget -q https://ftp.postgresql.org/pub/source/v17.1/postgresql-17.1.tar.gz -O postgres.tar.gz" did not complete successfully: exit code: 4
>
> As I mentioned in my initial review comment, it should be an easy fix,
> adding the && to the end of that line. Curious how you've tested this,
> though, if that is breaking.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ElementsProject/lightning/pull/7827#issuecomment-2525673902>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEEDCTXDFR63PRDBW6GRUL2EQU5FAVCNFSM6AAAAABR4456JGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRVGY3TGOJQGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-09 09:28 UTC, s373nZ commented
Not seeing any new changes. Did you forget to `git push` your updated code?

2024-12-09 22:38 UTC, closed without merging