askrene: add runtime of getroutes to the logs
ElementsProject/lightning pull request #7932
Opened 2024-12-11 11:39 UTC by Lagrang3

Add log information about the runtime of getroutes.

2024-12-12 20:35 UTC, Lagrang3 commented
Putting this into draft. As I am thinking we could do more than runtime statistics and even broadcast these values
in a "message" to listening plugins.

2025-03-20 23:21 UTC, rustyrussell requested changes

2025-03-24 06:58 UTC, Lagrang3 commented on plugins/askrene/askrene.c
> +	rq_log(tmpctx, rq, LOG_INFORM, "get_routes completed in %" PRIu64 " ms",
It will be DEBUG then.

2025-03-24 06:58 UTC, Lagrang3 commented on plugins/askrene/askrene.c
> +	return msec;
I missed that. Thanks.

2025-07-10 14:07 UTC, merged